trigger:  
- main

stages: 

- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Npm@1
      inputs:
        command: 'install'
        workingDir: 'frontend'

    - task: Npm@1
      inputs:
        command: 'custom'
        workingDir: 'frontend'
        customCommand: 'run build'

    - task: CopyFiles@2
      inputs:
        Contents: 'frontend/build/**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
            


# - stage: Deploy
#   jobs: 
#   - job: Deploy
#     pool: 
#       vmImage: 'ubuntu-latest'  
    
#     steps:    
#     - task: DownloadBuildArtifacts@1
#       inputs:
#         buildType: 'current'
#         downloadType: 'single'
#         artifactName: 'drop'
#         downloadPath: '$(System.ArtifactsDirectory)'
        
#     - task: AzureRmWebAppDeployment@4
#       inputs:
#         ConnectionType: 'AzureRM'
#         azureSubscription: 'Azure for Students(2ea47763-a202-468c-b00b-d986f6bafb35)'
#         appType: 'webAppLinux'
#         WebAppName: 'azuretestdevopsk'
#         packageForLinux: '$(System.DefaultWorkingDirectory)/drop'
#         RuntimeStack: 'STATICSITE|1.0'
    